### ISSUE TITLE
Устаревшие пакеты

### ISSUE THREAD

**Issue by crayxt** [Tigro/spin-kickstarts-rfremix#7]
Добрый день,
При сборке образа Гнома (Fedora 21, 64-bit) выдает следующую отладочную информацию

```
No such package cairo-freeworld to remove
No such package thai-scalable-fonts-compat to remove
No such package freetype-infinality to remove
No such package vlgothic-fonts-common to remove
```

**Comment by Tigro** [comment]
Приветствую. Не страшно.
14.11.2014 14:33 пользователь "Baurzhan Muftakhidinov" <
notifications@github.com> написал:
