### ISSUE TITLE
Добавить пакеты казахского языка

### ISSUE THREAD

**Issue by crayxt** [Tigro/spin-kickstarts-rfremix#8]
Добрый день,

Нельзя ли добавить два пакета в сборки, а именно `hunspell-kk` и `libreoffice-langpack-kk`?
Я понимаю что дистрибутив ориентирован на русскоязычных пользователей, но установкой этих двух пакетов получаем поддержку и для казахского языка) Ценой пары мегабайт.

**Comment by Tigro** [comment]
Здравствуйте.

Сделал: https://github.com/RussianFedora/rfremix-kickstarts/commit/5befe197773e910cd8cd6b39af384d66fa11cf12

и для 24-й.

**Comment by crayxt** [comment]
@Tigro большое спасибо!
